image: bycedric/expo-gitpod

tasks:
  - init: yarn install
    command: yarn start
    openIn: bottom

vscode:
  extensions:
    - dbaeumer.vscode-eslint

ports:
  # Metro bundler
  - port: 8081
    onOpen: ignore
  # Expo bundler 
  - port: 19000
    onOpen: ignore
    visibility: public # broken on iOS due to redirects not being followed
  - port: 19001
    onOpen: ignore
    visibility: public
  # Expo devtools
  - port: 19002
    onOpen: ignore # broken because of websocket opening on localhost
  # Expo web
  - port: 19006
    onOpen: open-preview
